/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoregistroestudiantes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deiberh
 */
public class RegistroPrincipal extends javax.swing.JFrame {
        /**
     * Creates new form RegistroPrincipal
     */
    String M [][] = new String [10][5];
    int i = 0;
    String [][] Registro;
    ListaEstudiantes frame = new ListaEstudiantes();
    AgregarOP2 frame2 = new AgregarOP2();
    public RegistroPrincipal() {
        initComponents();
        Genero.add(Hembra);
        Genero.add(Macho);
        Registro = new String [4][5];        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        jPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Macho = new javax.swing.JRadioButton();
        Hembra = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ciclo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ingles = new javax.swing.JCheckBox();
        Coaching = new javax.swing.JCheckBox();
        Programacion = new javax.swing.JCheckBox();
        opcion = new javax.swing.JButton();
        opcion2 = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        Estudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel2.setText("Registro de estudiantes");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Macho.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Macho.setText("Masculino");

        Hembra.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Hembra.setText("Femenino");
        Hembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HembraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Identificacion:");

        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Genero:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Ciclo:");

        Ciclo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Ciclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Java", "Python", "Base de Datos" }));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Datos de las materias");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Materias:");

        ingles.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ingles.setText("Inglés");
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });

        Coaching.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Coaching.setText("Coaching");

        Programacion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Programacion.setText("Programación");

        opcion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        opcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoregistroestudiantes/Plus.png"))); // NOI18N
        opcion.setText("Agregar Op1");
        opcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionMouseClicked(evt);
            }
        });

        opcion2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        opcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoregistroestudiantes/Plus.png"))); // NOI18N
        opcion2.setText("Agregar Op2");
        opcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion2MouseClicked(evt);
            }
        });
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        salir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoregistroestudiantes/No.png"))); // NOI18N
        salir.setText("Salir");

        Estudiantes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Estudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoregistroestudiantes/alumno.png"))); // NOI18N
        Estudiantes.setText("Lista de estudiantes");
        Estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstudiantesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Coaching)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Programacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Macho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Hembra)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(118, 118, 118))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcion)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estudiantes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcion2)
                                .addGap(18, 18, 18)
                                .addComponent(guardar)
                                .addGap(18, 18, 18)
                                .addComponent(salir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Macho)
                    .addComponent(Hembra))
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingles)
                    .addComponent(Coaching)
                    .addComponent(Programacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion2)
                    .addComponent(guardar)
                    .addComponent(salir)
                    .addComponent(opcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estudiantes)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxtActionPerformed

    private void HembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HembraActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inglesActionPerformed

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion2ActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        // TODO add your handling code here:
        String identificacion = IDtxt.getText();
        String ciclo = Ciclo.getSelectedItem().toString();
        String genero = Macho.isSelected()?"Masculino":"Femenino";
        String nombre = nombretxt.getText();
        String materia = " ";
        if (ingles.isSelected()) {
            materia += "Ingles ";
        }
        if (Coaching.isSelected()) {
            materia += "Coaching ";
        }
        if (Programacion.isSelected()) {
            materia += "Programacion";
        }
        M[i][0] = nombre;
        M[i][1] = identificacion;
        M[i][2] = genero;
        M[i][3] = ciclo;
        M[i][4] = materia;       
        
        String V [] = {M[i][1],M[i][0],M[i][2],M[i][3],M[i][4]};
        frame2.list.addElement("La identificacion del estudiante: "+identificacion+"\n"+"El nombre del estudiante: "+nombre+"\n"+"El genero del estudiante es: "+genero+"\n"+"El estudiante se encuentra en el ciclo: "+ciclo+"\n"+"Cursas las amterias: "+materia );
        i++;
         
        frame.lista.addRow(V);
        
        JOptionPane.showMessageDialog(null, "Estudiante Guardado");
        limpiar();
        
    }//GEN-LAST:event_guardarMouseClicked

    private void opcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion2MouseClicked
        // TODO add your handling code here:
        frame2.setVisible(true);
        
    }//GEN-LAST:event_opcion2MouseClicked

    private void opcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionMouseClicked
        // TODO add your handling code here:
        String identificacion = IDtxt.getText();
        String ciclo = Ciclo.getSelectedItem().toString();
        String genero = Macho.isSelected()?"Masculino":"Femenino";
        String nombre = nombretxt.getText();
        String materia = " ";
        if (ingles.isSelected()) {
            materia += "Ingles ";
        }
        if (Coaching.isSelected()) {
            materia += "Coaching ";
        }
        if (Programacion.isSelected()) {
            materia += "Programacion";
        }
        AgregarOP1 frame = new AgregarOP1();
        frame.txtarea.setText("Nombre: "+nombre+"\n"+"Identificacion: "+identificacion+"\n"+"Genero: "+genero+"\n"+"Ciclo: "+ciclo+"\n"+"Materias: "+materia);
        frame.setVisible(true);
    }//GEN-LAST:event_opcionMouseClicked

    private void EstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudiantesMouseClicked
        // TODO add your handling code here:
        frame.setVisible(true);
    }//GEN-LAST:event_EstudiantesMouseClicked
    private void limpiar (){
        nombretxt.setText(" ");
        IDtxt.setText(" ");
        Genero.clearSelection();
        Ciclo.setSelectedItem("seleccionar");
        ingles.setSelected(false);
        Coaching.setSelected(false);
        Programacion.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ciclo;
    private javax.swing.JCheckBox Coaching;
    private javax.swing.JButton Estudiantes;
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JRadioButton Hembra;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JRadioButton Macho;
    private javax.swing.JCheckBox Programacion;
    private javax.swing.JButton guardar;
    private javax.swing.JCheckBox ingles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JButton opcion;
    private javax.swing.JButton opcion2;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
